version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/repo/demo-java/testng/
          keys:
            - demo-java-testng-{{ checksum "pom.xml" }}
            - demo-java-testng
      - run:
          name: "Setup Maven Dependencies"
          command: |
            mvn clean install
            mvn dependency:go-offline
      - run:
          name: "Install and Launch Sauce Connect Tunnel"
          background: true
          command: |
            curl https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY}
            wget --retry-connrefused --no-check-certificate -T 60 localhost:4445  # wait for app to be ready
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
        name: "Run Maven Tests"
        command: |
          mvn test-compile
          mvn clean test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test